abstract: Custom errorhandling in deployed applications
author: Andreas Marienborg  C<< <andreas@startsiden.no> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Action-RenderView-ErrorHandler
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Action::RenderView: 0
version: 0.0100
