--- #YAML:1.0
name:               Catalyst-Action-RenderView-ErrorHandler
version:            0.100164
abstract:           Custom errorhandling in deployed applications
author:
    - Andreas Marienborg <andremar@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.30
build_requires:
    base:                 0
    Catalyst:             0
    Catalyst::Controller:  0
    Catalyst::Test:       0
    Catalyst::View:       0
    Catalyst::View::TT:   0
    FindBin:              0
    HTTP::Request::AsCGI:  0
    Test::More:           0.96
    Text::Diff:           0
requires:
    Carp:                 0
    Catalyst::Action::RenderView:  0
    Catalyst::View::TT:   0
    Class::Inspector:     0
    Moose:                0
    Moose::Role:          0
    MRO::Compat:          0
    strict:               0
    warnings:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
